site_name: LabelImg3D
site_url: http://shijie.chd.gold:2999/LabelImg3D
site_dir: public
repo_url: http://git.chd.gold:3000/shijie/LabelImg3D/
nav:
    - Home: index.md
    - Usage: usage.md
    - Proofs: proofs.md
    - About: about.md
# theme: readthedocs
theme: material
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js