site_name: LabelImg3D
site_url: http://shijie.chd.gold:2999/LabelImg3D
site_dir: public
repo_url: http://git.chd.gold:3000/shijie/LabelImg3D/
nav:
    - index.md
    - Introduction:
      - introduction/introduction.md
      - introduction/installation.md
      - introduction/format.md
    - Usage:
      - usage/usage.md
    - Dataset:
      - dataset/kitti.md
    - Proof:
      - proof/KITTI_to_LabelImg3D.md
      - proof/LabelImg3D_to_KITTI.md
    - about.md
# theme: readthedocs
theme: material
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js