# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1535, 935)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vtk_panel = SLabel3DAnnotation(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel.sizePolicy().hasHeightForWidth())
        self.vtk_panel.setSizePolicy(sizePolicy)
        self.vtk_panel.setMinimumSize(QtCore.QSize(600, 600))
        self.vtk_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vtk_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vtk_panel.setObjectName("vtk_panel")
        self.horizontalLayout.addWidget(self.vtk_panel)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1535, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Load_Scenes = QtWidgets.QAction(MainWindow)
        self.action_Load_Scenes.setObjectName("action_Load_Scenes")
        self.action_Save_Scenes = QtWidgets.QAction(MainWindow)
        self.action_Save_Scenes.setObjectName("action_Save_Scenes")
        self.actionHome = QtWidgets.QAction(MainWindow)
        self.actionHome.setObjectName("actionHome")
        self.actionEnd = QtWidgets.QAction(MainWindow)
        self.actionEnd.setObjectName("actionEnd")
        self.actionPrevious = QtWidgets.QAction(MainWindow)
        self.actionPrevious.setObjectName("actionPrevious")
        self.actionNext = QtWidgets.QAction(MainWindow)
        self.actionNext.setObjectName("actionNext")
        self.action_Delete_Model = QtWidgets.QAction(MainWindow)
        self.action_Delete_Model.setObjectName("action_Delete_Model")
        self.menu.addAction(self.action_Load_Scenes)
        self.menu.addAction(self.action_Save_Scenes)
        self.menuEdit.addAction(self.actionHome)
        self.menuEdit.addAction(self.actionEnd)
        self.menuEdit.addAction(self.actionPrevious)
        self.menuEdit.addAction(self.actionNext)
        self.menuEdit.addAction(self.action_Delete_Model)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.action_Load_Scenes.setText(_translate("MainWindow", "&Load Scenes"))
        self.action_Load_Scenes.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_Save_Scenes.setText(_translate("MainWindow", "&Save Scenes"))
        self.action_Save_Scenes.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionHome.setText(_translate("MainWindow", "Home"))
        self.actionHome.setShortcut(_translate("MainWindow", "Home"))
        self.actionEnd.setText(_translate("MainWindow", "End"))
        self.actionEnd.setShortcut(_translate("MainWindow", "End"))
        self.actionPrevious.setText(_translate("MainWindow", "Previous"))
        self.actionPrevious.setShortcut(_translate("MainWindow", "W"))
        self.actionNext.setText(_translate("MainWindow", "Next"))
        self.actionNext.setShortcut(_translate("MainWindow", "S"))
        self.action_Delete_Model.setText(_translate("MainWindow", "&Delete Model"))
        self.action_Delete_Model.setShortcut(_translate("MainWindow", "X"))
from slabel3dannotation import SLabel3DAnnotation
