# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kitti_2_labelimg3d.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormKitti2LabelImg3D(object):
    def setupUi(self, FormKitti2LabelImg3D):
        FormKitti2LabelImg3D.setObjectName("FormKitti2LabelImg3D")
        FormKitti2LabelImg3D.resize(684, 91)
        self.gridLayout = QtWidgets.QGridLayout(FormKitti2LabelImg3D)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openFolder_Btn = QtWidgets.QPushButton(FormKitti2LabelImg3D)
        self.openFolder_Btn.setObjectName("openFolder_Btn")
        self.horizontalLayout.addWidget(self.openFolder_Btn)
        self.lineEdit_Edt = QtWidgets.QLineEdit(FormKitti2LabelImg3D)
        self.lineEdit_Edt.setObjectName("lineEdit_Edt")
        self.horizontalLayout.addWidget(self.lineEdit_Edt)
        self.btn_Run = QtWidgets.QPushButton(FormKitti2LabelImg3D)
        self.btn_Run.setObjectName("btn_Run")
        self.horizontalLayout.addWidget(self.btn_Run)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(FormKitti2LabelImg3D)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 1)

        self.retranslateUi(FormKitti2LabelImg3D)
        QtCore.QMetaObject.connectSlotsByName(FormKitti2LabelImg3D)

    def retranslateUi(self, FormKitti2LabelImg3D):
        _translate = QtCore.QCoreApplication.translate
        FormKitti2LabelImg3D.setWindowTitle(_translate("FormKitti2LabelImg3D", "Form"))
        self.openFolder_Btn.setText(_translate("FormKitti2LabelImg3D", "OpenFolder"))
        self.btn_Run.setText(_translate("FormKitti2LabelImg3D", "Run"))
